### ISSUE TITLE
Prepare wiki for i9

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_internet9#1]
Deploy a wiki. Ready for content submission.

- [x] initial structure
- [x] deployment i9 staging

**Comment by xmonader** [comment]
@sasha-astiadi what is going to be the domain for staging? we usually do wiki2 (2 suffix) for the sitename, is it going to be i92? or something else?

**Comment by Pishoy** [comment]
https://internet9.me https://info.internet9.me should be live now

**Comment by sasha-astiadi** [comment]
thanks!
